# Generated by Django 5.0.6 on 2024-06-10 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_producto', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='numeroOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('estado', models.CharField(default='En proceso')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cantidad_productos', models.IntegerField()),
                ('sub_precio_venta', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('tipo_descuento', models.CharField(max_length=1000)),
                ('total_precio_venta', models.IntegerField()),
                ('numero_orden', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1000)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(max_length=1000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField()),
                ('cantidad', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminInventario2.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='detalleVentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=1000)),
                ('correo_cliente', models.CharField(max_length=1000)),
                ('pedido', models.TextField(blank=True, null=True)),
                ('cantidad_productos', models.IntegerField()),
                ('numero_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='adminInventario2.ventas')),
            ],
        ),
    ]
