# Generated by Django 5.0.6 on 2024-06-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInventario2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='precio_venta',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
