# Generated by Django 5.0.6 on 2024-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInventario2', '0002_alter_detalleventas_numero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='numero_orden',
            field=models.IntegerField(),
        ),
    ]
