# Generated by Django 5.0.6 on 2024-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInventario2', '0002_ventas_precio_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='precio_venta',
            new_name='descuento',
        ),
        migrations.AddField(
            model_name='ventas',
            name='sub_precio_venta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='total_precio_venta',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
