# Generated by Django 5.0.6 on 2024-06-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInventario2', '0003_rename_precio_venta_ventas_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='tipo_descuento',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
