# Generated by Django 5.0.6 on 2024-06-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInventario2', '0004_alter_ventas_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
